Rational
nastygorodi/PROJECT-Groebner-Basis pull request #1
Opened 2020-10-13 14:52 UTC by nastygorodi

2020-10-13 15:34 UTC, DimaTrushin requested changes
Добавил пару общих замечаний. Правь, потом еще раз гляну.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +int gcd(int num, int denom) {
У этой функции есть стандартная версия в stl 
std::gcd
https://en.cppreference.com/w/cpp/numeric/gcd
Зачем нужна эта версия?

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +
Обернуть весь свой код в namespace-ы

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +private:
Убрать приватную часть класса в самый конец. Детали имплементации менее важны, чем интерфейс класса. По умолчанию хороший порядок такой:
1) public части
а) публичные using-и
b) публичные конструкторы, дестроукторы и assignment операторы
c) публичные нестатические методы сгруппированные по темам
d) публичные статические и friend методы
2) protected часть
3) private часть
a) приватные методы
b) приватные данные

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    int numerator_, denominator_;
Никогда не определяй данные на одной строке. Это плохая привычка. Она тебя подведет с указателями. Кроме того, это мешает задать значения по умолчанию переменным.
int numerator_ = 0;
int denominator_ = 1;
Теперь, когда ты создаешь объект класса и в конструкторе не указываешь явную инициализацию переменной numerator_ ей всегда будет присваиваться значение 0, аналогично с denominator_.

PS отличная идея выбрать trainling underscore, чтобы отличать переменные класса от локальных переменных методов.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    Rational(int numerator = 0, int denominator = 1) {
1) Лучше не использовать конструкторы с дефолтными параметрами. Вместо этого можно использовать дефолтные инициализаторы членов класса. Сами инициализаторы -- это значения, которые ты присваиваешь членам класса, как выше
int numerator_ = 0;
int denomenator_ = 1;
у тебя уже есть. Потому тут можно убрать значения по умолчанию, а вместо него написать дефолтный конструктор
Rational() = default;

2) У конструктора есть такая вещь как список инициализации. Дело в том, что когда ты создаешь объект класса, то создаются все его поля, в твоем случае  numerator_ и denominator_. Эти поля надо инициализовать. Их можно инициализовать во время конструирования. Это эффективнее.
Rational(int numerator, int denominator) : numerator_(numerator), denominator_(denominator) {
reduce();
}
Тогда значение numerator будет присвоего при создании numerator_ в памяти. В твоем варианте, сначала создается numerator_ с мусорным значением (или если есть дефолтные значения, то дефолтным значением), а потом ты в теле конструктора присваиваешь значения. А в моем варианте значение помещается сразу при конструировании в память. Это почти не имеет значения для встроенных типов, но имеет катострофическое значение для тяжелых типов и дисциплинирует.

3) Очень хорошая идея добавить reduce для поддержания инвариантов.

4) Стоит добавить 
assert(denominator_ != 0);
в начале конструктора перед reduce(); в моей версии.
Это проверка на ошибки. Если пользователь создает дробь с нулевым знаменателем.
Вообще есть две стратегии реакции на ошибки:
a) Кинуть исключение.
b) Упасть с assert-ом.
(a) используется, когда программа должна работать и встретила ошибку, которая не связана с программистом, а связана с ошибкой среды, где она работает. Например операционная система не дала открыть файл или не дала выделить память и т.д. В этом случае программа ничего не может сделать и кидает исключение.
(b) нужна, чтобы отлавливать свои ошибки, ошибки программиста. Если ты создаешь дробь с нулевым знаменателем, то это вина твоя как программиста, потому ты должна себя поймать за руку, что ты не сделала нужную проверку. Особенность assert следуюая: в дебаг режиме она падает, если условие внутри не верно, а релиз режиме она не генерирует никакого кода. Потому assert не влияет на производительность в релизе.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +        Rational x;
Это можно сократить до 
return *this;
Тогда автоматически вернется копия текущего объекта.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +        Rational x;
Можно сократить до
Rational x(-numerator_, denominator_);
return x;
либо до
return Rational(-numerator_, denominator_);
Второй вариант предпочтительнее, так как не использует ненужное имя x.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    Rational& operator+=(const Rational& addendum) {
Я бы предпочел использовать other в качестве аргумента, чем addendum. Аналогично для других аргументов. Но может быть я безграмотрный и не знаю правильных слов на английском.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +        numerator_ = numerator_ * addendum.denominator_ + denominator_ * addendum.numerator_;
Не самый дружелюбный к overflow метод перемножения. Если уж ты используешь gcd, то можно и lcm использовать. Но можно оставить пока и так.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    int numerator_, denominator_;
- Я бы рекомендовал использовать
long long
ибо int слишком быстро переполнится. Для кросс платформености можно использовать std::int64_t

- Я бы в начале класса сдела публичные юзинги
using IntegralType = std::int64_t;
и типы переменных вел в виде IntegralType. Тогда во всех метода не надо будет переделывать int под новые значения. Например
Rational(IntegralType numerator, IntegralType denominator_)...
IntegralType numerator() const {...}
и т.д.
Если ты изменишь внутренний тип, то не надо будет менять во всех местах тип.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +        int cur = divider.numerator_;
Зачем нужна эта временная переменная?
Кроме того, не хватает 
assert(divider.numerator_ != 0);

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    Rational& operator++() {
Такой операции НЕ должно быть в интерфейса рациональных чисел. Она непонятно что означает. Исключить.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    Rational& operator--() {
Такой операции НЕ должно быть в интерфейса рациональных чисел. Она непонятно что означает. Исключить.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    Rational operator++(int) {
Такой операции НЕ должно быть в интерфейса рациональных чисел. Она непонятно что означает. Исключить.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    Rational operator--(int) {
Такой операции НЕ должно быть в интерфейса рациональных чисел. Она непонятно что означает. Исключить.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    Rational current = first;
Очень хорошо! Как раз сработает copy ellision и нет дупликации кода. Единственное я бы имя сделал result, а не current.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +bool operator==(const Rational& first, const Rational& second) {
Этот оператор можно сделать friend методом. Но даже без этого, так как у тебя все определено в header-е, то компилятор заинлайнит вызов функций для числителя и знаменателя.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +     first.denominator() == second.denominator();
Вообще говоря, эта функция работает не правильно. Если числитель 0, то знаменатель не имеет значения. Да у тебя конструктора поддерживает инвариант, что нулевое число создается в виде 0/1. Однако операторы сложения и умножения не поддерживают этот инвариант! Потому есть два пути
1) Сделать здесь проверку на ноль числителя отдельным случаем.
2) Поддерживать инвариант, что если числитель 0, то знаменатель 1.
На мой взгляд 2-ой подход предпочтительнее. Потому что это дает корректный знаменатель нуля, он будет одинаковый для всех нулевых рациональных чисел. Я бы сделал метод normilize_if_zero() или что-то в этом духе, который будет проверять числитель на ноль, и если он нулевой, делает знаменатель 1. И добавил бы его во все модифицирующие методы вида +=, -= и т.д. Тогда внешние операторы не надо будет менять.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +    return !(first == second);
Очень хорошо.

2020-10-13 15:34 UTC, DimaTrushin commented on Rational.h
> +
Для рациональных чисел еще можно добавить операторы сравнения <, >, <=, >=

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +private:
убрала приватную часть в конец класса

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +int denominator_ = 1;
убрала определение данных в одной строке

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +    Rational() = default;
задефолтила конструктор

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +        return *this;
сократила до *this

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +using IntegralType = std::int64_t;
публичный юзинг

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +        assert(divider.numerator_ != 0);
скажем нет временным переменным и скажем да assert-у

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +bool operator<(const Rational& first, const Rational& second) {
добавила операторы сравнения <, >, <=, >=

2020-10-13 17:12 UTC, nastygorodi commented on Rational.h
> +namespace Groebner {
убрала свою функцию НОДа и обернула код в namespace

2020-10-13 17:15 UTC, nastygorodi commented on Rational.h
> +namespace Groebner {
убрала свою ф-ию нахождения НОДа и обернула код в namespace

2020-10-18 14:31 UTC, nastygorodi commented on Rational.h
> +    out << current.numerator();
update вывода, если знаменатель 1

2020-10-20 08:49 UTC, DimaTrushin requested changes
Добавил пару мелких замечаний. Исправишь и можно заливать в мастера.

2020-10-20 08:49 UTC, DimaTrushin commented on Rational.h
> +using IntegralType = std::int64_t;
это приватный using. Так как он идет в приватной части. Публичный означал
public:
using IntegralType = std::int64_t;
отличие в том, что публичный тип ты можешь запросить у класса, например
Rational::IntegralType my_numerator;

2020-10-20 08:49 UTC, DimaTrushin commented on Rational.h
> +
Я бы добавил конструктор
Rational(IntegralType numberator) : numerator_(numerator) {...}
Тогда знаменатель задефолтится (reduce() понадобится в теле конструктора). Но при этом можно будет делать так
Rational r = 1;
или эквивалентно
Rational r(1);
И будет разрешена конвертация IntegralType в Rational в выражениях вида 1 + x и x + 1, где x -- это Rational.

Если хочешь запретить конвертацию (что не думаю имеет смысл делать), то можно сделать так
explicit Rational(IntegralType numberator) : numerator_(numerator) {...}
Тогда ты все еще можешь написать
Rational r(1); или Rational r = 1; 
Однако в выражениях
1 + x и x + 1 будет требоваться явно написать Rational(1) + x и x + Rational(1). Однако, я не вижу никакого ризона запрещать такую конвертацию. Дело в том, что вариант
1 + x; с неявной конвертацией
Rational(1) + x; с явной
ведут себя абсолютно одинаково с точки зрения исполнения и инструкций на машинном коде, однако для программиста удобнее первый вариант. Единственная ситуация, в которой мы хотели бы избежать такой конвертации, если бы у нас был отдельный оператор
Rational operator(IngegralType first, const Rational& second); и подобные
который выполняет эту работу эффективнее. Но у нас такого нет и потому бессмысленно запрещать конвертацию.

Последнее замечание. Я подумал, что так как мы не хотим запрещать конвертацию, то три конструктора, которые я предложил
Rational() = default;
Rational(IntegralType numberator) : numerator_(numerator) {...}
Rational(IntegralType numerator, IntegralType denominator) : numerator_(numerator), denominator_(denominator) {...}
вместе с
IntegralType numerator_ = 0;
IntegralType denominator_ = 1;
Эквивалентно твоему одному конструктору
Rational(IntegralType numerator = 0, IntegralType denominator = 1) : numerator_(numerator), denominator_(denominator) {...}
Единственная разница в том, что в моем случае я могу конструктора от одного аргумента сделать explicit и запретить конвертацию если надо. 
В сухом остатке, это было не лучшее предложение изменить сигнатуру твоего конструктора в этом конкретном случае. Но зато теперь у тебя есть понимание, какие еще есть подходы и на что это влияет.

2020-10-20 08:49 UTC, DimaTrushin commented on Rational.h
> +private:
В приватной части порядок такой
1) методы
2) данные
Потому переставь void reduce() перед приватными данными и добавь между ними пустую строчку для читаемости.

2020-10-20 08:49 UTC, DimaTrushin commented on Rational.h
> +bool operator>(const Rational& first, const Rational& second) {
return second < first;

2020-10-20 08:49 UTC, DimaTrushin commented on Rational.h
> +bool operator<(const Rational& first, const Rational& second) {
Для этого оператора я бы предложил более короткую имплементацию
return (first - second).numerator() < 0;

Кроме того, общее замечание. Если ты возвращаешь значение или бросаешь исключение в if-е, то else не нужен. Например, можно было бы написать так
if ((first - second).numerator() < 0)
  return true;
return false;
Я еще и скобки тут не пишу. Так намного более читаемо. Но так как возвращаемое значение в точности совпадает с проверяемым в if, это можно укоротить до указанной выше версии.

2020-10-20 12:22 UTC, nastygorodi commented on Rational.h
> +
я исправила все, что ты писал в последнем ревью =)

2020-10-20 13:00 UTC, DimaTrushin requested changes
Еще одна мелочь и все.

2020-10-20 13:00 UTC, DimaTrushin commented on Rational.h
> +    Rational(IntegralType numerator) : numerator_(numerator) {
Порядок конструкторов идет по количеству аргументов: в начале дефолтный, потом от одного аргумента, потом от двух и так далее.

2020-10-20 15:05 UTC, DimaTrushin approved these changes
Отлично, можно заливать.

2020-10-20 15:08 UTC, merged