поле остатков
nastygorodi/PROJECT-Groebner-Basis pull request #2
Opened 2020-10-18 14:42 UTC by nastygorodi

2020-10-20 08:21 UTC, DimaTrushin requested changes
Я внес несколько комментариев. Основная проблема -- ошибка дизайна. У тебя модуль по которму считаюсят остатки является динамическим параметром. Надо переделать класс F (отличное название =) ) в 
template < std::int64_t mod > 
class Modular {
...
};
В связи с этим изменением все операторы придется загнать внутрь в виде friend-ов. Я про это сделал замечание только к сложению, но это касается и сравнения и оператора вывода.
После того как переделаешь, я еще по конструкторам сделаю пару замечаний. Пока не могу их конкретно сказать.

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +    IntegralType n_ = 1;
Вот это ошибка дизайна. У тебя модуль, по которому читаются остатки хранится в каждом элементе. Это плохо. Вот почему. Пусть у тебя есть два элемента
x = 3 (5) и y = 4 (7)
То есть остаток 3 по модулю  5 и остаток 4 по модулю 7. Это элементы из разных полей и ты не должна уметь их складывать. Но так как у тебя x и y -- это элемента типа F, то их можно будет сложить и компилятор не ругнется! Это должны быть элементы разных типов. То есть основание, по которому ты берешь остаток должно быть часть сигнатуры класса, а не частью элемента.

Надо сделать так
template < std::int64_t mod > 
class Modular {
...
};
Тогда у тебя будет делаться так
Modular<5> x = 3;
Modular<7> y = 4;
и ты уже не можешь сложить x и y. Это элементы разных типов.

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +        while (number_ < 0) {
Здесь не нужен цикл.
Для целых типов операции / и % обладают следующим свойством
a / b + a % b == a
всегда верно. Детали https://en.cppreference.com/w/cpp/language/operator_arithmetic раздел Multiplicative operators.
Кроме этого a / b всегда отбрасывает дробную часть в десятичной запяси. То есть если результат положительный, то округляется вниз, а если отрицательный, то округляется вверх.

Потому ты можешь для любых знаков сделать
number_ % mod;
Получится нужный остаток, но может быть отрицательный, тогда можно либо if-ом проверить и прибавить mod, либо можно прибавить mod и еще раз взять остаток
((number_ % mod) + mod) % mod;
вот это всегда сделает остаток неотрицательным в три такта cpu без условных переходов.

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +        assert(n_ != 0);
если mod будет статическим параметром, то на него динамические assert-ы не нужны будут. Надо будет поставить статические. Напишу об этом в соответствующем разделе.

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +        number_ /= divider.number_;
Это делается либо через алгоритм евклида. Если mod -- основание, number_ -- остаток, то
(number_, mod) = 1, а значит по евклиду у тебя есть a * number_ + b * mod = 1. Значит a -- это обратный. Но надо писать евклида.
Либо это делается через малую теорему ферма, а именно. number_ ^ {mod - 1} = 1 по модулю mod. То есть тебе нужно написать функцию быстрого возведения в степень pow и обратный тогда будет pow(number_, mod - 2).

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +        reduce();
Очень хорошо, что выделила в отдельную функцию reduce();

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +
Можно еще добавить explicit конструктор, если mod будет статическим параметром компиляции.

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +    IntegralType number() const{
Не уверен, что хорошая мысль иметь эту функцию в публичном интерфейсе. Какая ее роль? Ее роль для остатка дать канонический остаток. Тогда ее лучше так и назвать: canonical_remainder(); Или как-нибудь аналогично.

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +F operator+(const F& first, const F& second) {
Так как я предложил сделать класс F (с новым именем Modular) шаблонным, то у тебя не получится так просто сделать friend оператор в этом случае. Есть три разных подхода к тому, как поступать в этом случае. Они описаны тут
https://web.mst.edu/~nmjxv3/articles/templates.html
еще вот тут есть
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.cbclx01/friends_and_templates.htm
Если кратко. То функции бывают двух типов в плюсах: обычные и шаблонные. Принципиальная разница между ними, что у обычных функций компилятор допускает конвертацию аргументов, а у шаблонных нет. У операторов мы обычно хотим конвертацию. Например,
Modular<5> x = 3;
x + 1;
1 + x;
мы хотим, чтобы обе строчки сработали, мы хотим, чтобы 1 конвертировалось в Modular<5>(1) и потом сложилось в обоих случаях. Это возможно, только если operator+ будет НЕ шаблонным. А единственный путь в этом случае -- объявлять inline friend оператор в теле шаблона. К сожалению ничего другого сделать нельзя. Подробнее прочтешь в ссылке.

2020-10-20 08:21 UTC, DimaTrushin commented on F.h
> +    out << current.number();
здесь можно в одну строчку
return out << current.number();

2020-10-20 20:57 UTC, nastygorodi commented on Modular.h
> +
постаралась исправить ошибку дизайна

2020-10-21 10:47 UTC, DimaTrushin requested changes
С шаблонной частью получилось хорошо. Есть некоторые огрехи с евклидом (ему не место в интерфейсе класса, плохое название, плохо оформлены выходные параметры и т.д.). Я постарался все огрехи адресовать. Еще есть некоторые мелочи в плани написания кода.

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +};
У namespace не надо ; после закрывающейся фигурной скобки!

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +        };
Никогда не ставь ; после }. Единственная ситуация, когда это делатеся -- определение класса. Во всех других случаях это может привести к ошибке. Особенно тут. Дело в том, что здесь ; рассматривается как пустая команда после блока if. Очень часто это может превратиться во что-нибудь такое
if(condition) ; {
  operations;
}
Так как плюсам пофигу на форматирование, это означает
if(condition) 
  ; 
{
  operations;
}
То есть если условие верное, то не делай ничего, а потом выполни operations внутри выделенного блока в фигурных скобках.

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +class Modular {
Я бы вот тут в приватной части добавил 
static_assert(mod > 0, "The modulus must be positive!");
Тогда эта штука гарантирует, что Modular не будет компилироваться с отрицательными значениями mod и выдаст ошибку при компиляции подобного.

Другой вариант -- через enable_if вообще отключить компиляцию для отрицательных значений модуля. Это работает так
template < std::int64_t mod, class = std::enable_if_t<(mod > 0)> >
class Modular {
В этом случае при не положительных значениях такой шаблон будет отключен и при попытке откомпилировать Modular<-3> компилятор ругнется на то, что с таким параметром шаблона нет.

Первый подход лучше тем, что мы можем сообщить пользователю класса о том, что именно за ошибка была сделана в виде комментария в static_assert.

Проверку на простоту добавлять не стоит. Потому что ты можешь захотеть в будущем работать с этим классом, как с кольком остатков для необязательно простых оснований mod. Но инвариант положительности нам нужен.

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +        return Modular(mod - number_);
Из-за того, что конструктор и так вызывает reduce() и нормализует вид числа, то тут тебе не надо об этом задумываться и можно просто написать Modular(- number_); Но это не принципиально.

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +    IntegralType reduce_Euclid (IntegralType a, IntegralType b, IntegralType& x, IntegralType& y) {
С этой функцией есть несколько проблем:
1) Название. Совершенно не понятно, что она делает, что она возвращает. Потому что у тебя есть честно возвращаемое значение и еще есть ссылки на аргументы. Как я понимаю, это gcd_extended.
2) Есть понятие входных и выходных параметров.
void func(int in_param1, conat A& in_param2, double* out_param1, A* out_param2);
Если ты хочешь возвращать информацию через аргументы, то принято делать так:
- входные аргументы передаются by value для встроеных типов или by const reference для пользовательских типов и идут перев входными параметрами.
- выходные параметры передаются by pointer и идут в самом конце. Это нужно для того, чтобы тот, кто вызывает функцию знал, чего его переменную собираются модифицировать. Например
void f(int in, int& out);
void g(int in, int* out);
Сравни два вызова
int x = 0;
int y = 4;
f(x, y);
g(x, &y);
У пользователя первой функции f нет никаких намеков на то, что y после вызова f изменится.
3) Вообще выходные параметры люди сейчас не жалуют, потому что можно возвращать std::tuple и биндить возвращаемое значение. Например
std::pair<int, double> f(int x, double y);
auto [u, v] = f(2, 1.3);
4) Необходимость в выходных параметрах у тебя возникла из-за рекурсии. Эту функцию можно переписать в  нерекурсивном виде, в виде цикла. В таком случае отпадет необходимость передавать изменяющиеся параметры и не будет тратиться стек.
5) Имена переменных. С такими именами совершенно непонятно, что за что отвечает. Либо надо написать комментарий про инварианты (что всегда не очень желательно ибо комментарий может устареть и не меняться синхронно с кодом), либо сделать нормальные имена переменным (но бывает, что это не очень получается и надо написать, какой у нас инвариант).
6) Этой функции не место в публичном интерфейсе Modular. Дело в том, что это общая математическая функция, которая должна жить отдельно. Ее могут использовать и другие классы для других целей. Как минимум ее надо вынести наружу, может в отдельный namespace, может в отдельный файл или класс.

В сухом остатке. Я бы вытащил эту функцию из класса, поменял название и сделал не рекурсивной. Это решит все проблемы.

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +        IntegralType x_, y_;
Никогда не делай _ в именах локальных переменных функции. Тогда начинает казаться, что это переменные класса и это сильно запутывает. Ты нарушаешь свою собственную договоренность.

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +    bool solution_Euclid (IntegralType a, IntegralType b, IntegralType c, IntegralType& x, IntegralType& y, IntegralType& g) {
- У этой функции аналогичные проблемы. Она не относится к классц Modular, у нее плохое название, выходные параметры скрыты.
 - Альтернатива возврату bool -- возвращать optional, например 
std::optional < std::pair < IntegralType, IngetralType > > 
если делится, то возвращается пара, если не делится, то optional не определен.

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +        assert(divider.number_ != 0);
Правильное условие
std::gcd(divider.number_, mod) == 1

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +        Modular x, y, g;
Зачем ты зваодишь переменные класса Modular, если в итоге пользуешься лишь IntegralType переменными?

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +        if (solution_Euclid(divider.number_, mod, number_, x.number_, y.number_, g.number_)) {
После проверки
assert(std::gcd(divider.number_, mod) == 1);
в начале, это условие обязано быть верным всегда и его можно убрать. А значит можно и упростить саму функцию solution_Euclid (как ее интерфейс, так и ее имплементацию).

2020-10-21 10:47 UTC, DimaTrushin commented on Modular.h
> +    IntegralType reduce_Euclid (IntegralType a, IntegralType b, IntegralType& x, IntegralType& y) {
Еще хотел обратить внимание, что тут ты забыла про const, потому что не думала про эту функцию как метод Modular, однако сделала ее методом Modular. Это еще один намек на то, что этой функции тут не место.

2020-10-22 11:51 UTC, nastygorodi commented on Modular.h
> +using IntegralType = std::int64_t;
создала отдельный namespace для решения уравнений вида ax+by = c;

2020-10-22 11:51 UTC, nastygorodi commented on Modular.h
> +static_assert(mod > 0, "The modulus must be positive!");
теперь компилятор ругнется

2020-10-25 21:05 UTC, DimaTrushin requested changes
Я сделал несколько замечаний по дизайну и предложений по исправлению проблем.

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +using namespace Equations;
Никогда ни при каких условиях не делай using namespace внутри другого namespace. Ты таким образом засоряешь текущее пространство имен Groebner именами из пространства имен Equations. Это по сути равносильно тому, что ты объявила бы эти методы внутри namespace Groebner вместо Equation, только на уровне бинарного кода имена будут другие.
Связано это с тем, что namespace можно открыть в любом файле и добавить в него новых имен. Для namespace любая колизия имени -- это трагедия. Когда ты пишешь локальное имя внутри namespace Equation, ты можешь быть уверена, что скрыла его, а потом эта строчка тебе все испортит, если такое же имя встретится в Groebner.

Какие есть альтернативы:
1) Просто объявить все функции внутри namespace Groebner.
2) Использовать using namespace только в той функции, где используются имена из этого namespace.
3) Не использовать using namespace.

Можно пойти по второму или третьему пути.

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +        std::optional<std::pair<IntegralType, IntegralType>> solution = solve_equation(divider.number_, mod, number_, param_1, param_2);
У тебя уже выше стоит assert, потому тут можно вызывать функцию, которая знает, что нод какой надо. Потому предлагаю такой редизайн:
1) Пусть функция solve_equation возвращает std::pair < IntegralType, IntegralType >, а не optional. Но внутри solve_equation надо поставить assert на проверку этого условия.
2) В таких случаях лучше писать
auto solution = solve_equation(...);
Чтобы тип автоматом определялся.

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +        if (solution != std::nullopt) {
У optional есть специальный метод has_value() для проверки, что в нем что-то есть. Но я думаю, что нам теперь optional вообще ни к чему.

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +IntegralType gcd_extended (IntegralType coeff_1, IntegralType coeff_2, IntegralType& x, IntegralType& y) {
У тебя выходные параметры передаются по ссылке. Это плохо. Я уже писал почему. Со стороны вызывающего функцию, не видно, что параметры меняются. Сейчас можно сделать лучше.
struct GCDResult {
IntegralType gcd;
IntegralType first_coefficient;
IntegralType second_coefficient;
};

GcdResult gcd_extended(IntegralType value1, IntegralType value2) {
...
return {gcd, x, y};
}

Эти модификации сделаю количество аргументов у функции меньше, код короче и не так вытянутым в высоту.

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +std::optional<std::pair<IntegralType, IntegralType>> solve_equation (IntegralType coeff_1, IntegralType coeff_2, IntegralType coeff_3, IntegralType& param_1, IntegralType& param_2) {
Здесь я бы так же сделал редизайн функции
struct DiophantineSolution {
IntegralType first_coefficient;
IntegralType second_coefficient;
};

DiophantineSolution solve_equation(IntegralType value1, IntegralType value2, IntegralType rhs) {
auto result = gcd_extended(value1, value2);
assert(rhs % result.gcd == 0);
...
}

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +    //находили для ax + by = (a, b) --> чтобы получить решение диофантова ур-я \cdot const/(a, b)
Такие коммантарии надо писать не внутри функции, а перед ней, используя названия переменных в функции и объясняя, что она делает.

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +using IntegralType = std::int64_t;
Вот тут появилась проблема под названием code duplication. У тебя тип IntegralType определен в двух разных местах и эти типы являются зависимыми: 1) здесь, 2) внутри класса Modular. Это говорит об ошибке дизайна. А именно, эти функции, когда ты их вынесла наружу теперь не предполагают, что тип должен быть обязательно Modular < ... > ::IntegralType. Они должны уметь рабоать с любым целочисленным типом. То есть по сути это должны быть шаблонные функции вида
template < class TIntegralType >
... gcd_extended(TIntegralType value1, TIntegralType value2) {...}
Только надо соответствующим образом GcdResult подправить (сделать шаблонным).

В этом случае пропадет лишняя зависимость от фиксированного типа и функции станут reusable и с другими типами. Также можно шаблонами разрешить эти функции только для арифметических типов, например
template < class TIntegralType, class = std::enable_if_t < std::is_integral_v < TIntegralType > > >

2020-10-25 21:05 UTC, DimaTrushin commented on Modular.h
> +        std::optional<std::pair<IntegralType, IntegralType>> solution = solve_equation(divider.number_, mod, number_, param_1, param_2);
По сути using namespace Equation был нужен только для этой строчки.

2020-10-26 13:54 UTC, nastygorodi reviewed
я постаралась поправить свои косяки

2020-10-26 13:54 UTC, nastygorodi commented on Modular.h
> +template <class TIntegralType, class = std::enable_if_t <std::is_integral_v <TIntegralType>>>
сделала функции шаблонными

2020-10-26 13:54 UTC, nastygorodi commented on Modular.h
> +        auto solution = Equations::solve_equation<IntegralType>(divider.number_, mod, number_);
убрала using namespace внутри Groebner

2020-10-26 22:13 UTC, DimaTrushin requested changes
Сделал еще несколько замечаний по поводу новых функций. Теперь их стоит вынести в отдельный header.
В остальном все очень хорошо.
Из полезных функций можно было бы добавить функцию возведения в степень (в виде френда), но я думаю, что этого сейчас делать не надо. Если вдруг понадобится, то сделаем потом, когда увидим необходимость в ней. Иначе это все затянется на ненужных мелочах.

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +        return {divider, x, y};
Это все можно сократить до строчки
if (value2 == 0)
  return {value1, 1, 0};

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +    TIntegralType divider, quotient, remainder, x, x2, x1, y, y2, y1;
Никогда не заводи переменные заранее!
Например все эти переменные тебе не нужны сейчас. Кроме того, divider тебе вообще не нужен никогда. Надо объявлять все переменные только там, где они нужны и сразу присваивать им значения. Если ты не можешь присвоить значение переменной, то ты ее воодишь слишком рано. Заодно получается, что объявлять в одной строчке несколько переменных -- плохо.
Компилятор хорошо умеет оптимизировать время жизни локальных переменных и чем ближе они к своему использованию объявлены, тем лучше он справляется.

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
>      x2 = 1;
TIntegralType x2 = 1;
TIntegralType x1 = 0;
TIntegralType y2 = 0;
TIntegralType y1 = 1;

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +        quotient = value1 / value2;
TIntegralType quotient = value1 / value2;
TIntegralType remainder = value1 - quotient * value2;
TIntegralType x = x2 - quotient * x1;
TIntegralType y = y2 - quotient * y1;

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +    divider = value1;
Начиная отсюда и до конца все можно заменить одной строчкой
return {value1, x2, y2};

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +    while (value2 > 0) {
Что если value2 было отрицательным? Правильное условие 
while(value2 != 0)

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +    DiophantineSolution<TIntegralType> solution;
Эта переменная не нужна. Раз ты ее тут не инициализируешь. Убрать.

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +    solution.first_coefficient = result.first_coefficient * rhs / result.gcd;
Вместо строчек отсюда и до конца надо написать
return {result.first_coefficient * rhs / result.gcd, result.second_coefficient * rhs / result.gcd};
Тогда и переменная solution не понадообится.

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
> +    TIntegralType first_coefficient;
Что-то мне кажется, что я длинноватые имена выбрал. Может first и second будет лучше?

2020-10-26 22:13 UTC, DimaTrushin commented on Modular.h
>  namespace Equations {
Теперь эти функции и структуры выглядят так, что их место в отдельном header-е. Просто их теперь можно хотеть подключить куда-нибудь, но при этом без подключения мономов. Раз это общие функции. Можно выделить Diophantine.h файли или что-то в этом духе (IntegralHelper.h, IntegralEquations.h, придумай что-нибудь или выбери сама.)

2020-10-27 06:07 UTC, nastygorodi commented on Modular.h
> +#include"Diophantine.h"
вынесла namespace Equations в отдельный header

2020-10-27 09:36 UTC, DimaTrushin reviewed
Тут совсем мелочи. Зачем-то встретилась точка с запятой после определения функции. И нет единообразия в оформлении кода. А именно пробелы стоят по-разному.

2020-10-27 09:36 UTC, DimaTrushin commented on Modular.h
> +    };
А тут зачем точку с запятой???

2020-10-27 09:36 UTC, DimaTrushin commented on Modular.h
>  template < std::int64_t mod >
Осталось только пробелы все сделать единообразными.

2020-10-27 09:41 UTC, nastygorodi commented on Modular.h
> +    };
случайно

2020-10-27 09:47 UTC, nastygorodi commented on Modular.h
> +    }
убрала запяточие

2020-10-27 09:47 UTC, nastygorodi commented on Modular.h
> +template <std::int64_t mod>
удалила пробелы

2020-11-13 13:46 UTC, DimaTrushin approved these changes
Отлично.
Единственное заметил вот какую вещь. У тебя файл Modular.h требует подключение Diophantine.h, а они в разных ветках. То есть ты пишешь вслепую? Или тестируешь где-то в другом месте в локальной ветке?

2020-11-13 14:04 UTC, merged