Add Monomial
nastygorodi/PROJECT-Groebner-Basis pull request #3
Opened 2020-10-24 10:31 UTC by nastygorodi

2020-10-25 21:45 UTC, DimaTrushin requested changes
Я добавил несколько замечаний. Основное касается работы с std::map и в частности тонкостей относительно оператора operator[].
Обрати внимание на предложение по добавлению функции degree_of_variable. Она может сильно упростить тебе жизнь в разных местах. Может быть только называние стоит придумать короче.
Еще было несколько мелких и не очень замечаний. В частности по разделению типов для индекса и для степени.

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +    using IntegralType = std::int64_t;
Вот это не очень хорошо по двум причинам.
1) У тебя тип для индекса переменной и для степени переменный может быть разным. Потому надо два using-а
using IndexType = std::int64_t;
using DegreeType = std::int64_t;
2) В мономе степень переменной должна быть неотрицательной. Потому надо либо будет поддерживать инвариант, что степень больше нуля (или больше или равна нуля). Либо гарантировать это типом, например
using DegreeType = std::uint64_t;

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +            degrees_[pair.first] = pair.second;
Здесь есть несколько проблем
1) pair.first может повторяться в initializer_list. И ты можешь этого желать или не желать. То есть индекс одной и той же переменной указан несколько раз с разными степенями. Ты по сути полагаешь в этом случае степень последнему значению.
2) pair.second может быть равным нулю. Тогда ты запихнула не существующую переменную (раз она идет в нулевой степени) в свою мапу.
3) Ты используешь медленный оператор operator[]. Если ты создаешь объект, то лучше использовать emplace или try_emplace.
https://en.cppreference.com/w/cpp/container/map/emplace
https://en.cppreference.com/w/cpp/container/map/try_emplace
emplace делает следующее: оно конструирует нужный элемент прямо на месте во время выделения памяти. Если элемент не существовал в map, то он помещается в map, если существовал, то он сначала строится, а потом удаляется (что есть потеря времени).
try_emplace так же конструирует нужный элемент прямо на месте, но если такой элемент уже существовал, то он ничего не делает (не создает ненужный элемент и не теряет время).
Я бы написал
if(pair.second != 0)
  degrees_.try_emplace(pair.first, pair.second);
В этом случае у тебя поместится только первый элемент в мапу, а остальные будут проигнорированы.

Если ты хочешь сообщить о задваивании, как об ошибке, то можно проверить результат try_emplace
if(pair.second != 0) {
  auto result = degrees_.try_emplace(pair.first, pair.second);
  assert(result.second);
}
Этот assert проверяет, что элемент был вставлен.

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +        for (auto& degree : (*this).degrees_) {
здесь *this не надо, можно просто degrees_
кроме этого const auto& degree
for( const auto& degree : degrees_)

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +            if (other.degrees_[degree.first] < degree.second) {
Тут есть серьезная проблема. Оператор operator[] всегда возвращает ссылку на значение в map. А потому, если элемента нет, то он создается
https://en.cppreference.com/w/cpp/container/map/operator_at
Кроме того, этот оператор по этой причине не является const. Именно по этой причине этот код не скомпилируется, когда other не является const! Я думаю именно с этим связано отсутствие const в сигнатуре для этого оператора для его аргумента, у тебя это просто не скомпилилось.

Тут надо поступать по-другому. Надо для начала найти с помощью find есть ли в other нужный моном. find вернет итератор. Если он end, то значит нет, если он не end, то можно у него узнать степень переменной в other.

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +    bool operator|(Monomial& other) const{
Я бы не стал использовать оператор | для этих целей, хотя в математике такой и используется. Лучше уж назвать функцию
bool is_divisible_by(const Monomial& other) const {
...
}
Это будет намного читаемее. Я даже не сразу понял, что тут за функция написана. Пришлось потупить чуть-чуть.
Кроме того, обрати внимание на const Monomial&. Этот метод обязан НЕ менять other ни при каких условиях. Если у тебя функция не компилируется с const, это НЕ значит, что его надо убирать, потому что он тут нужен. Это значит, что у тебя где-то ошибка и ты используешь неконстантные методы внутри этого метода. Я уже написал в чем именно проблема и как ее править в другом комментарии.

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +            (*this).degrees_[degree.first] -= degree.second;
Еще надо проверить, что если степень стала равна нулю, то эту переменную надо удалить из монома.
Так же убери *this он тут НЕ нужен.

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +            (*this).degrees_[degree.first] += degree.second;
*this здесь не нужен.

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +        for (auto& degree : divider.degrees_) {
const auto& degree

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +    friend Monomial gcd_of_monomials(Monomial& first, Monomial& second) {
Плохая сигнатура, функция должна иметь вид
 friend Monomial gcd_of_monomials(const Monomial& first, const Monomial& second) {
...
}
Еще лучше сделать так
static Monomial gcd(const Monomial& first, const Monomial& second) {
...
}
Тогда это имя будет спрятано внутри class Monomial и будет найдено по ADL и не надо будет замусоревать Groebner namespace именем этой функции.

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +            result.degrees_[degree.first] = std::min(degree.second, second.degrees_[degree.first]);
Проблема тут в том, что operator[] добавляет элемент, как я уже писал. Я бы на твоем месте сдела вот как. Определи функцию у Monomial следующего вида
DegreeType degree_of_variable(IndexType index) const {
auto iter = degrees_.find(index);
if (iter == degrees_.end() )
  return 0;
return iter->second;
}
Тогда эта функция безопасная и возвращает степень любой переменной независимо от того, есть она в map или нет. Тогда можно gcd находить так: бежать по переменным одного монома как по map, а к степеням другого монома обращаться через эту функцию.
for(const auto& degree_pair : first.degrees_) {
  auto gcd_degree = std::min(degree_pair.second, second.degree_of_variable(degree_pair.first));
  if (gcd_degree > 0)
    result.degrees_.emplace(degree_pair.first, gcd_degree);
}

2020-10-25 21:45 UTC, DimaTrushin commented on Monomial.h
> +            if (degree.second != 0) {
Я бы на твоем месте поддерживал инвариант, что second != 0. Тогда тут надо поставить
assert(degree.second);
и убрать этот scope

2020-10-26 22:45 UTC, DimaTrushin requested changes
Добавил несколько технических замечаний. Еще сделал комментарий по поводу форматирования кода. Есть программы автоматизирующие этот процесс. Сам я пользуюсь не самой лучшей AStyle. Но есть стандарт в индустрии clang format. Его можно поставить и под виндой и где угодно. Большинство таких утилит интегрируются с популярными IDE. Я дал ссылки на две из них.

2020-10-26 22:45 UTC, DimaTrushin commented on Monomial.h
> +            auto it = other.degrees_.find(degree.first);
Сейчас, когда есть функция degree_of_variable эту часть можно упростить максимально, а именно
if (other.degree_of_variable(degree.first) < degree.second)
  return false;
Потому что by design она работает всегда, даже когда пары нет в контейнере. Это безопасная функция.

2020-10-26 22:45 UTC, DimaTrushin commented on Monomial.h
> +    bool divides(const Monomial& other) const{
Мне не нравятся такие названия функций, потому что не ясно, что они проверяют логическое условие.
does_divide
выглядит лучше, но все равно паршиво, на мой взгляд
is_divisibly_by
куда читабельнее. Но тогда проверка делимости в другую сторону (что не проблема совсем).

Хотя может быть я и запариваюсь. Я посмотрел сейчас assert с этой функцией, выглядит читаемо. Посмотри еще комментарий к assert-у в строке 48.

2020-10-26 22:45 UTC, DimaTrushin commented on Monomial.h
> +        assert(divider.divides(*this));
Мне кажется, что вот такой assert выглядит лучше
assert(is_divisible_by(divider));
Что думаешь? Хотя этот тоже читаемый.

2020-10-26 22:45 UTC, DimaTrushin commented on Monomial.h
> +            degrees_[degree.first] -= degree.second;
Я бы вместо функции reduce в конце этого метода делал удаление индивидуально на каждой итерации. Дело в том, что ты бежишь по divider.degrees_, а модифицируешь degrees_ в this. Потому технически ты можешь менять второй map. Кроме того, тут у тебя все изменения локальные, у тебя каждая переменная встречается один раз (ключи уникальные). Потому если у тебя тут получился 0 и ты его удалишь, то к этому элементу не придется возвращаться. Для этого можно использовать удаление по ключу.
if (degrees_[degree.first] == 0)
  degrees_.erase(degree.first);

2020-10-26 22:45 UTC, DimaTrushin commented on Monomial.h
> +            result.degrees_.emplace(std::make_pair(degree.first, gcd_degree));
Здесь не надо make_pair, должно быть
result.degrees_.emplace(degree.first, gcd_degree);
Разница вот в чем.
Вариант emplace(key, value) сразу создает внутри map пару по ключу и значению
Вариант emplace(std::make_pair(key, value)) создает временную пару, а потом делает move временной пары внутрь map. Что для пары равносильно копированию данных.

То есть в твоем случае есть одно лишнее копирование. Обрати на это внимание. Когда ты создаешь объекты, все методы плюсовых контейнеров заточены так, чтобы пробрасывать аргументы конструкторов и не создавать временных объектов. Это одна из основных фишек плюсового кода. при создании объекта, если ты создаешь временный -- это обычно ошибка. Вместо создания временного объекта, сразу направь необходимые данные на создания нужного объекта.

2020-10-26 22:45 UTC, DimaTrushin commented on Monomial.h
> +        auto it = degrees_.end();
Вот это полный кошмар. Запутанная непонятная логика. По хорошему в виде цикла это пишется так
auto it = degrees_.cbegin();
while (it != degrees_.cend()) {
  if (it ->second == 0)
   it = degrees_.erase(it);
 else 
  ++it;
}
Дело в том, что erase удаляет элемент и возвращает итератор на следующий после удаленного. То есть если степень не ноль, ты просто передвигаешь итератор вперед, а если степень ноль, то удаляешь и итератор переставляешь на следующий элемент.

2020-10-26 22:45 UTC, DimaTrushin commented on Monomial.h
> +    Monomial (std::initializer_list<std::pair<IndexType, DegreeType>> list) {
Я заметил у тебя не постоянство кода вида
void function();
void function ();
Или
void function() const{
void function() const {
Такого НЕ должно быть. Чтобы не умереть от ручных правок таких вещей, придуманы автоматические форматировщики кода. Я пользуюсь
Astyle (не самая лучшая вещь, но я когда начинал не знал чем пользоваться).
http://astyle.sourceforge.net/
Еще есть стандарт в индустрии clang format
https://clang.llvm.org/docs/ClangFormat.html
Можно загуглить как его ставить под винду. Я сам хочу этим заняться.

Идея этих штук такая, ты запускаешь его на нужном файле (или файлах) и он автоматически форматирует файл в соответствии с настройками. Многие IDE поддерживают их интеграцию. Например я пользуюсь QtCreator, и у него есть поддержка трех подобных программ (этих двух и еще одной какой-то). Там можно настроить, чтобы правила форматирования применялись при сохранении файла. И в итоге мне вообще не надо задумываться над такими вещами, как форматирование. Все применяется автоматом.

2020-10-27 09:11 UTC, nastygorodi commented on Monomial.h
> +    bool is_divisible_by(const Monomial& other) const{
мне и предыдущий вариант нравился, но раз уж тебе так нравится is_divisible_by , согласна оставим так =)

2020-10-27 09:11 UTC, nastygorodi commented on Monomial.h
> +    void reduce() {
Я вот ее не удалила, но нигде не использую. Как думаешь, может ли она в будущем для чего-то понадобиться, или убьем reduce()?

2020-10-31 20:54 UTC, nastygorodi commented on Monomial.h
> +    const std::map<IndexType, DegreeType>& get_degrees() const{
add get_degrees()

2020-10-31 20:55 UTC, nastygorodi reviewed
добавила get_degrees() для порядков

2020-11-13 14:03 UTC, DimaTrushin requested changes
Остался небольшой баг с проверкой наделимость (неаккуратно развернула бинарную функцию). И еще одно запяточие. Остальное хорошо. Поправь, как я предложил и можно будет мерджить.

2020-11-13 14:03 UTC, DimaTrushin commented on Monomial.h
> +        for (const auto& degree : degrees_) {
Теперь эта функция  не верно имплементирована. Тебе надо бежать по степеням other, а не по степеням this
 for (const auto& degree : other.degrees_) {
  if (degree_of_variable(degree.first) < degree.second)
    return false;
}
return true;
Потому что ты хочешь проверить все степени переменных в мономе, на который ты хочешь делиться, а не те, которые есть в твоем this. Например, this может быть 1 -- все степени 0, тогда твой for loop будет пустым и вернется true для любого монома other, что не верно.

Хотел сказать, что такие косяки бывают, когда переворачиваешь функцию неаккуратно. У тебя же раньше была проверка наоборот, ты проверяла делимость other на this и потому было правильно. Бывает.

2020-11-13 14:03 UTC, DimaTrushin commented on Monomial.h
>      };
Вот тут запяточие осталось.

2020-11-13 14:03 UTC, DimaTrushin commented on Monomial.h
> +    void reduce() {
В одном из коммитов код для этой функции останется. Если понадобится можно вернуть. Так что пока предлагаю удалить, чтобы не мешалась.

2020-11-13 14:20 UTC, nastygorodi commented on Monomial.h
> +    }
запяточие убрала

2020-11-13 14:20 UTC, nastygorodi commented on Monomial.h
> +    bool is_divisible_by(const Monomial& other) const {
сначала не поняла, почему не права была, потом все еще не поняла, но в итоге вроде понятно, что накосячила, хотя мои локальные запросы программа обрабатывала нормально...

2020-11-13 14:20 UTC, nastygorodi commented on Monomial.h
> +private:
убрала пока что никому не нужный reduce()

2020-11-13 14:40 UTC, DimaTrushin commented on Monomial.h
> +    bool is_divisible_by(const Monomial& other) const {
Попробуй
Monomial a;
Monomial b{{1,1}};
assert(!a.is_divisible_by(b));
По дефолту a должно быть 1, а b -- это x_1, тогда явно не должно быть делимости. Однако, по предыдущим правилам будет косяк, потому что ты проверяешь, что все переменные, которые встретились в a имеют степень не меньше, чем в b. Но это пустое множество условий, которое будет выполнено.

2020-11-13 14:45 UTC, DimaTrushin approved these changes
Остались мелкие косметические придирки вроде пробелов и скобок. Но я не буду уже блочить код.

2020-11-13 14:45 UTC, DimaTrushin commented on Monomial.h
> +    const std::map<IndexType, DegreeType>& get_degrees() const{
Кстати, опять пробела нет после const

2020-11-13 14:45 UTC, DimaTrushin commented on Monomial.h
> +            if (degree_of_variable(degree.first) < degree.second)
Обратил внимание на одну непостоянность. Ты иногда пишешь
if (some condition) {
  do_something();
}
А иногда
if (some condition)
  do_something();
Без скобок. Надо быть более постоянной. Я не будут сейчас ничего блочить. Это можно уже потом косметикой сделать в мастере.

2020-11-15 17:02 UTC, merged