Add Diophantine.h
nastygorodi/PROJECT-Groebner-Basis pull request #4
Opened 2020-10-27 06:11 UTC by nastygorodi

2020-10-27 09:29 UTC, DimaTrushin requested changes
Осталось несколько мелких замечаний.

2020-10-27 09:29 UTC, DimaTrushin commented on Diophantine.h
> +}
новая строка в конце

2020-10-27 09:29 UTC, DimaTrushin commented on Diophantine.h
> +    TIntegralType divider, quotient, remainder;
Вот эта строка больше не нужна.
1) divider вообще нигде не используется.
2) quotient и remainder и так определяются ниже в цикле.

2020-10-27 09:29 UTC, DimaTrushin commented on Diophantine.h
> +//solve an equation ax + by = (a, b)
Комментарий в рассинхроне с функцией
1) a и b вообще нигде не встречаются в коде
2) x и y встречаются в коде, но значат совсем не то, что написано в комментарии.

Если править комментарий, то я бы сделал так
// solve an equation ax + by = (a, b)
// where a = value1, b = value2
// return value is {(a,b), x, y}

Если выбирать между писать комментарий и не писать комментарий, лучше выбрать второй вариант. Код должен быть self-explanatory. То есть ты читаешь код и должно быть понятно из имен переменных и методов, что код делает. Комментарии нужны очень редко, но когда нужны, их надо писать так, чтобы они не мешали пониманию, не обманывали и не вводили в заблуждение. На этут тему есть хороший текст в книге Clean Code, посвященный комментариям в коде. Надо будет мне тебе кинуть ссылку на нее.

2020-10-27 09:29 UTC, DimaTrushin commented on Diophantine.h
> +template <class TIntegralType, class = std::enable_if_t <std::is_integral_v <TIntegralType>>>
Я бы перенес это определение после функции gcd_extended и перед функцией solve_equation, чтобы это определение было ближе к тому месту, где оно используется. Если пользователю solve_equation захочется понять, что за структуру та возвращает, ему не придется блуждать по коду в ее поиске.
Когда думаешь, где расположить тот или иной кусок кода, кроме естественных ограничений языка, важно задумываться о  такой характеристики как: количество прыжков по коду, которое нужно сделать его читателю. Связанные вещи должны быть рядом и чем сильнее они связаны, тем ближе они должны быть.

2020-10-27 09:29 UTC, DimaTrushin commented on Diophantine.h
> +    auto result = gcd_extended<TIntegralType>(value1, value2);
Здесь можно написать просто
auto result = gcd_extended(value1, value2);
Без указания шаблонного параметра. Дело в том, что когда вызывается шаблонная функция, то для них в плюсах есть отдельное правило: ее шаблонные параметры определяются из типов ее аргументов. Так как оба аргумента имют тип TIntegralType, то best match будет функция gcd_extended<TIntegralType>.

Этим трюком специально пользуются, когда надо скрыть огромное количество шаблонных параметров от пользователя. Нужный код заворачивают в шаблонную функцию, чтобы все параметры (или большинство) определить из аргументов.

2020-10-27 09:39 UTC, nastygorodi commented on Diophantine.h
> +#include<iostream>
поправила косяки

2020-11-13 13:45 UTC, DimaTrushin approved these changes
Отлично.

2020-11-13 14:05 UTC, merged