Add Order.h
nastygorodi/PROJECT-Groebner-Basis pull request #5
Opened 2020-10-31 21:01 UTC by nastygorodi

2020-11-08 16:47 UTC, nastygorodi reviewed
постаралась исправить все косяки, которые запомнила с консультации

2020-11-08 16:47 UTC, nastygorodi commented on Order.h
> +class Reverse {
добавила class Reverse

2020-11-08 16:47 UTC, nastygorodi commented on Order.h
> +public:
попыталась избавиться от повторяющихся кусков кода

2020-11-08 16:47 UTC, nastygorodi commented on Order.h
> +class Lex {
пыталась избавиться от повторов в коде

2020-11-13 14:24 UTC, nastygorodi commented on Order.h
> +    bool operator()(const Monomial& first, const Monomial& second) const {
добавила оператор скобочки (для порядка в полиномах)

2020-11-13 14:37 UTC, DimaTrushin requested changes
Сделал несколько предложений по рефакторингу. У тебя местами есть лишнии функции. Кроме того, местами, можно сократить код использованием STL алгоритмов.
Так же предполагалось добавить operator() во все классы, чтобы любой из них можно было использовать с STL. Я внес соответствующие замечания в релевантных местах.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +class Lex {
- Перемудрила. Не было никакой необходимости выносить код в отдельную функцию, которая используется 1 раз.

- Я бы написал используя функцию mismatch
https://en.cppreference.com/w/cpp/algorithm/mismatch

const auto& [position1, position2] = std::mismatch(first.get_degrees().begin(), first.get_degrees().end(), second.get_degrees().begin(), second.get_degrees().end());
Тогда position1 и position2 будут указывать на первое место, где значения отличаются (либо индексы переменных, либо степени).
Дальше надо разобрать случай, если хотя бы один из них end. А если они оба не end, то можно сравнить std::pair. Поумолчанию они сравниваются лексикографически.
https://en.cppreference.com/w/cpp/utility/pair/operator_cmp
смотри (3) версию.
В итоге надо написать что-то вроде
if(position2 == second.get_degrees().end())
  return false;
В этом случае либо position1 == end() и значит они равны, либо position1 < end() и значит first больше, чем second. Теперь знаем, что position2 не end() и проверяем position1
if( position1 == first.get_degrees().end())
  return true;
Мы знаем, что position2 != end() значит, в этом случае first короче second, а значит и меньше.
А теперь когда оба не указывают на end пишем
return *position1 < *position2;
Звездочка вернет пару из map и оператор < сравнит их сначала по первой first, потом по second. То есть сначала по индексу переменной и если они одинаковые, то по степени. Как раз то, что нам надо.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +        return Lex::compare(begin1, end1, begin2, end2);
Кстати, тут не надо было писать Lex::compare, достаточно было просто compare, так как мы и так видим это имя внутри класса Lex.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +                             begin1->first == begin2->first && begin1->second == begin2->second) {
Если что на будущее строчка
begin1->first == begin2->first && begin1->second == begin2->second
эквивалентна
*begin1 == *begin2

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +public:
Добавь в публичную часть после cmp оператор operator()
bool operator()(const Monomial& first, const Monomial& second) const {
  return cmp(first, second);
}
Это для совместимости с STL класса Lex.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +        return Deg::compare(first.get_degrees().begin(), first.get_degrees().end(),
- Вот здесь compare -- лишняя функция. Можно было написать сразу код
auto deg1 = total_degree(first.get_degrees().begin(), first.get_degrees().end());
auto deg2 = total_degree(second.get_degrees().begin(), second.get_degrees().end());
return deg1 < deg2;

- Лучше избавиться от привычки ставить скобки вокруг возвращаемого аргумента. Здесь это ни на что не повлияет, но есть ситуации, где это может дать неприятный эффект.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +public:
Ты на самом деле сделала неплохой рефактор, но ввела одну лишнюю функцию compare.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +public:
Надо добавить оператор operator()
bool operator()(const Monomial& first, const Monomial& second) const {
return cmp(first, second);
}
Для совместимости с STL.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +    bool operator()(const Monomial& first, const Monomial& second) {
добавь const у оператора.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +public:
Добавь оператор operator()
bool operator()(const Monomial& first, const Monomial& second) const {
return cmp(first, second);
}
Для совместимости с STL.

2020-11-13 14:37 UTC, DimaTrushin commented on Order.h
> +public:
Добавь оператор operator()
bool operator()(const Monomial& first, const Monomial& second) const {
return cmp(first, second);
}
Для совместимости с STL.

2020-11-15 17:47 UTC, nastygorodi commented on Order.h
> +class Lex {
сделала по-человечески : )

2020-11-15 17:47 UTC, nastygorodi commented on Order.h
> +    bool operator()(const Monomial& first, const Monomial& second) const {
везде, куда ты написал, подобавляла операторов скобочки для совместимости с STL

2020-11-15 18:31 UTC, nastygorodi commented on Order.h
> +        return position1->first > position2->first ||  (position1->first == position2->first && position1->second < position2->second);
исправила ошибку природы

2020-11-17 15:26 UTC, DimaTrushin requested changes

2020-11-17 15:26 UTC, DimaTrushin commented on Order.h
> +#include <algorithm>
Осталось тут добавить 
#pragma once
и все, отлично.

2020-11-17 16:22 UTC, nastygorodi commented on Order.h
> +#pragma once
добавила #pragma once

2021-06-09 18:38 UTC, DimaTrushin approved these changes

2021-06-09 18:58 UTC, merged