Polynomial.h
nastygorodi/PROJECT-Groebner-Basis pull request #6
Opened 2020-11-15 19:25 UTC by nastygorodi

2020-11-17 14:47 UTC, DimaTrushin requested changes

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +    const std::map<Monomial, Coeff, Reverse<Order>>& get_terms() const {
Сделать alias
using TermsContainer = std::map<Monomial, Coeff, Reverse<Order>>;

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +#include <initializer_list>
#pragma once
добавить во все хедеры

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +    Polynomial(std::initializer_list<std::pair<Monomial, Coeff>> terms) {
Стоит поменять местами Monomial и Coeff
std::pair<Coeff, Monomial>

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +    Coeff coeff_of_term(const Monomial& m) const {
coeff_of(...)

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +            if (coeff_of_term(term.first) == 0) {
Вот этот кусок с if-ом можно заменить на 
terms_[term.first] += term.second;
Здесь используется, что для Coeff дефолтное значение равно нулю, то есть объект Coeff() == 0.

Так как каждый коэффициент может обнулиться только после этой строчки. То вместо reduce можно сделать проверку и удаление прямо в этом месте.

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +        Polynomial result;
вместо result надо создать 
TermContainer result;

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +                auto check = result.terms_.try_emplace(term1.first * term2.first, term1.second * term2.second);
result[term1.first * term2.first] += term1.second * term2.second;

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +                assert(check.second);
assert тут лишний

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +        terms_ = result.terms_;
Лишнее копирование.
terms_ = std::move(result);
при условии, что result -- это std::map<...>

2020-11-17 14:47 UTC, DimaTrushin commented on Polynomial.h
> +
Можно добавить конструктор
Polynomial(Coeff coefficient) : terms_({Monomial(), std::move(coefficient)}) {
}
Либо
Polynomial(Coeff coefficient) {
terms_.emplace(Monomial(), std::move(coefficient));
}
Второй вариант предпочтительнее

2020-11-24 12:48 UTC, nastygorodi commented on Polynomial.h
> +#pragma once
#pragma once

2020-11-24 12:48 UTC, nastygorodi commented on Polynomial.h
> +    Polynomial(Coeff coefficient) {
конструктор по чиселке

2020-11-24 12:48 UTC, nastygorodi commented on Polynomial.h
> +                terms_.erase(term.first);
покороче и покрасивее

2020-11-24 12:48 UTC, nastygorodi commented on Polynomial.h
> +                result[term1.first * term2.first] += term1.second * term2.second;
исправилась

2020-11-24 12:48 UTC, nastygorodi commented on Polynomial.h
> +    TermsContainer terms_;
добавила TermsContainer как ты советовал

2021-01-04 18:52 UTC, nastygorodi commented on Polynomial.h
> +    Polynomial(const Monomial& m) {
добавила конструктор по моному

2021-01-04 18:52 UTC, nastygorodi commented on Polynomial.h
> +    Polynomial& operator-=(const Polynomial& other) {
оператор минус мне понадобился в алгоритмах, там дальше еще френдовый оператор минус

2021-04-13 18:44 UTC, nastygorodi commented on Polynomial.h
> +    void norm() {
теперь умеем делать полином с коэффициентом при главном мономе 1

2021-04-15 09:37 UTC, nastygorodi commented on Polynomial.h
> +    friend bool operator==(const Polynomial& first, const Polynomial& second) {
теперь можем сравнивать на равенство/ неравенство

2021-06-09 18:39 UTC, DimaTrushin approved these changes

2021-06-09 18:58 UTC, merged